---
nim_waku_cont_tag: 'deploy-status-{{ stage }}'
nim_waku_cont_name: 'nim-waku'
nim_waku_dns4_domain_name: '{{ dns_entry }}'
# Protocols
nim_waku_protocols_enabled: ['relay', 'filter', 'lightpush', 'store']
# Node Key
nim_waku_node_key: '{{lookup("bitwarden", "fleets/status/"+stage+"/nodekeys", field=hostname)}}'
# Ports
nim_waku_p2p_tcp_port: 30303
nim_waku_p2p_udp_port: 30303
nim_waku_metrics_port: 8008
nim_waku_rpc_tcp_port: 8545
nim_waku_rpc_tcp_addr: 0.0.0.0
# Limits
nim_waku_p2p_max_connections: 150
# SQLite store
nim_waku_sqlite_store: true
nim_waku_sqlite_retention_time: '30.days.seconds'
# Peer connecting
nim_waku_connect_consul_service_names: ['{{ nim_waku_cont_name }}', 'nim-waku-bridge']
nim_waku_connect_rpc_port: '{{ nim_waku_rpc_tcp_port }}'
# Discovery V5
nim_waku_disc_v5_enabled: true
nim_waku_disc_v5_enr_auto_update: true
nim_waku_disc_v5_port: 9000
# Consul Service
nim_waku_consul_success_before_passing: '{{ (stage == "prod") | ternary(2, 4) }}'
nim_waku_consul_failures_before_warning: '{{ (stage == "prod") | ternary(1, 2) }}'
nim_waku_consul_failures_before_critical: '{{ (stage == "prod") | ternary(4, 10) }}'

# Open LibP2P Ports
open_ports_default_comment: '{{ nim_waku_cont_name }}'
open_ports_default_protocol: 'tcp'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: '{{ nim_waku_p2p_tcp_port }}' }
  - { port: '{{ nim_waku_p2p_udp_port }}', protocol: 'udp' }
  - { port: '{{ nim_waku_disc_v5_port }}', protocol: 'udp' }
  - { port: '{{ nim_waku_metrics_port }}', chain: 'VPN', ipset: 'metrics.hq' }
  - { port: '{{ nim_waku_rpc_tcp_port }}', chain: 'VPN', ipset: '{{ env }}.{{ stage }}' }
