---
swap_file_size_mb: 2048

# Nim-Waku
nim_waku_cont_tag: 'deploy-status-{{ stage }}'
nim_waku_cont_name: 'nim-waku'
nim_waku_dns4_domain_name: '{{ dns_entry }}'
# Protocols
nim_waku_protocols_enabled: ['relay', 'filter', 'lightpush', 'store']
# Node Key
nim_waku_node_key: '{{lookup("bitwarden", "fleets/status/"+stage+"/nodekeys", field=hostname)}}'
# Ports
nim_waku_p2p_tcp_port: 30303
nim_waku_p2p_udp_port: 30303
nim_waku_websock_port: 443
nim_waku_metrics_port: 8008
nim_waku_rpc_tcp_port: 8545
nim_waku_rpc_tcp_addr: 0.0.0.0
# Limits
nim_waku_p2p_max_connections: 150
# SQLite store
nim_waku_sqlite_store: true
nim_waku_sqlite_retention_time: 1209600 # 14 days
# Discovery V5
nim_waku_disc_v5_enabled: true
nim_waku_disc_v5_enr_auto_update: true
nim_waku_disc_v5_port: 9000
# Websockets
nim_waku_websocket_enabled: true
nim_waku_websocket_secure_enabled: true
nim_waku_websocket_domain: '{{ dns_entry }}'
nim_waku_websocket_ssl_dir: '/etc/letsencrypt'
nim_waku_websocket_ssl_cert: '/etc/letsencrypt/live/{{ nim_waku_websocket_domain }}/fullchain.pem'
nim_waku_websocket_ssl_key: '/etc/letsencrypt/live/{{ nim_waku_websocket_domain }}/privkey.pem'
# Consul Service
nim_waku_consul_success_before_passing: '{{ (stage == "prod") | ternary(2, 4) }}'
nim_waku_consul_failures_before_warning: '{{ (stage == "prod") | ternary(1, 2) }}'
nim_waku_consul_failures_before_critical: '{{ (stage == "prod") | ternary(4, 10) }}'

# Peer connecting
waku_peers_rpc_port: '{{ nim_waku_rpc_tcp_port }}'
waku_peers_rpc_timeout: 20
waku_peers_rpc_retries: 5
waku_peers_consul_services:
  - { name: '{{ nim_waku_cont_name }}', env: '{{ env }}',  stage: '{{ stage }}' }
  # Temporarily disabled bridge. https://github.com/status-im/infra-status/issues/14
  #- { name: 'nim-waku-bridge',          env: '{{ env }}',  stage: '{{ stage }}' }

# LetsEncrypt via Certbot
certbot_docker_enabled: true
certbot_admin_email: 'devops@status.im'
certbot_containers_to_stop: ['{{ nim_waku_cont_name }}']
certbot_certs:
  - domains: [ '{{ nim_waku_websocket_domain }}' ]

# Open LibP2P Ports
open_ports_default_comment: '{{ nim_waku_cont_name }}'
open_ports_default_protocol: 'tcp'
open_ports_default_chain: 'SERVICES'
open_ports_list:
  - { port: '80', comment: 'Certbot verification' }
  - { port: '{{ nim_waku_p2p_tcp_port }}' }
  - { port: '{{ nim_waku_p2p_udp_port }}', protocol: 'udp' }
  - { port: '{{ nim_waku_disc_v5_port }}', protocol: 'udp' }
  - { port: '{{ nim_waku_websock_port }}' }
  - { port: '{{ nim_waku_metrics_port }}', chain: 'VPN', ipset: 'metrics.hq' }
  - { port: '{{ nim_waku_rpc_tcp_port }}', chain: 'VPN', ipset: '{{ env }}.{{ stage }}' }
