---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure Waku Nodes
  hosts: status-node
  serial: '{{ serial|default(3) }}'
  roles:
    - { role: infra-role-open-ports,  tags: open-ports  }
    - { role: infra-role-swap-file,   tags: swap-file   }
    - { role: infra-role-certbot,     tags: certbot     }
    - { role: infra-role-nim-waku,    tags: nim-waku    }
