---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./versioncheck.py
      changed_when: false

- name: Configure Waku Nodes
  hosts:
    - status.test
  roles:
    - { role: open-ports, tags: open-ports }
    - { role: swap-file,  tags: swap-file  }
    - { role: nim-waku,   tags: nim-waku   }
