---
- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  scm: git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  scm: git

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: bfd404dd92642e1d310f8ce40df97fcb9e33be98
  scm: git

- name: infra-role-nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: 6c7837b1f857379e7b66c8ce776ac050c7946705
  scm: git

- name: infra-role-certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: c7a5afe6a7d76f7c021041ec1e7df4f7e46cf374
  scm: git

- name: infra-role-postgres-ha
  src: git@github.com:status-im/infra-role-postgres-ha.git
  version: 9fbe3851b902f9873441c2b26a6d3a7e9d1525c7
  scm: git
