---
- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: 2860f5c720ae5803bc1838eb58da37969d8d8b90
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: 15fadc81c5bf709be3e0d6071cebb6d6d8287ea0
  scm: git

- name: certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: aa7daf1fe135375bb4295742e3c1566ee4aeffba
  scm: git
