---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 7280600c2c6cf532fdbbbb31481fdb068dd0573e
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: b711bbabd2dc3d9ce8b1c3a6e5bc785901db9d09
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 2b3d4e53856d6cc91ae5c5a342fd12f2bb96aa88
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: 1e5367c86a906d9b08c0d492f5d70a85d790ae37
  scm: git

- name: waku-peers
  src: git@github.com:status-im/infra-role-waku-peers.git
  version: 9d00e1b330ea89253a147a99b463fb42f58e570b
  scm: git
