---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: da1ff350bf5bf2f248230aa56ac778177a75b5f8
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: a701db9b634f2b16fe14f98da3cf6568f037b0db
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 7ee51839e6a032e6ca27dfb00951e897b5385609
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: cb2b857ba929cda4a5ba9859bd7de27adafdd16b
  scm: git
